import { Ad } from './types';

export const INITIAL_ADS: Ad[] = [];

export const DEMO_ADS: Ad[] = [
  {
    id: 'ad-1',
    title: 'Mitsubishi Express Campervan - Road-Trip Ready (WA Rego!)',
    description: 'Perfect companion for your Aussie adventure. We traveled from Sydney to Perth with absolutely no mechanic trouble. Fully equipped with a cozy double bed, custom kitchen setup in the rear, high-quality secondary battery (deep cycle) connected to a 35L fridge, and plenty of storage boxes underneath the bed. Comes with WA license plates which makes the Rego transfer 100% online and hassle-free, no mechanical inspection needed!',
    type: 'Van',
    equipmentState: 'Clé en main',
    regoState: 'WA',
    price: 8900,
    mileage: 284000,
    year: 2008,
    brand: 'Mitsubishi',
    model: 'Express',
    location: 'Perth',
    equipments: ['Lit convertible', 'Second Battery', 'Frigo', 'Réchaud gaz', 'Ustensiles de cuisine', 'Réservoir d\'eau', 'Convertisseur 12v-220v'],
    isPremium: true,
    image: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Maxime & Lea',
    whatsappNumber: '+33612345678',
    createdAt: '2026-05-20'
  },
  {
    id: 'ad-2',
    title: 'Toyota LandCruiser Prado 4x4 - Ready for the Outback & Gibb River Road',
    description: 'This legendary Prado is an absolute beast! Equipped with dual tanks (180L fuel capacity for the long stretches), 2-inch heavy-duty suspension, brand new Yokohama all-terrain tires, and a lockable drawer system. Includes a rooftop tent (Kings) set up in 2 minutes, pristine sleeping bags, camping chairs, and a solar shower. Engine is robust, serviced every 10,000 km (logbook provided). Ultimate 4WD capability to access remote beaches!',
    type: '4x4',
    equipmentState: 'Clé en main',
    regoState: 'QLD',
    price: 13500,
    mileage: 310000,
    year: 2005,
    brand: 'Toyota',
    model: 'LandCruiser Prado',
    location: 'Cairns',
    equipments: ['Tente de toit', 'Compresseur d\'air', 'Sangles de remorquage', 'Frigo', 'Table de camping', 'Deuxième batterie', 'Réservoir d\'eau'],
    isPremium: true,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Lukas',
    whatsappNumber: '+491761234567',
    createdAt: '2026-05-22'
  },
  {
    id: 'ad-3',
    title: 'Subaru Outback 2.5i - Clean Budget Station Wagon with Sleeping Setup',
    description: 'Super reliable AWD station wagon, ideal for 1 or 2 travelers on a budget. Extremely fuel efficient (8L/100km compared to 14L for 4x4s). We have fitted a thick mattress in the back (rear seats fold completely flat), custom window curtains for stealth camping, and includes all kitchen utensils, a solid cooler (icebox), and 2 sleeping bags. New brake pads, logbook complete. Perfect to start working on farms around NSW!',
    type: 'Station Wagon',
    equipmentState: 'Clé en main',
    regoState: 'NSW',
    price: 4800,
    mileage: 235000,
    year: 2007,
    brand: 'Subaru',
    model: 'Outback',
    location: 'Sydney',
    equipments: ['Matelas arrière', 'Panneaux solaires (pliants)', 'Glacière', 'Réchaud gaz', 'Ustensiles de cuisine', 'Rangement plastique'],
    isPremium: false,
    image: 'https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Chloe',
    whatsappNumber: '+33698765432',
    createdAt: '2026-05-23'
  },
  {
    id: 'ad-4',
    title: 'Ford Falcon Wagon - Low KM & Cheap Farm Commuter',
    description: 'Selling my sturdy Ford Falcon. Heavy-duty inline 6-cylinder engine that runs forever. Super cold AC, spacious boot space where you can fit a double mattress or tons of harvest gear. Located currently in Dubbo, perfect for backpackers about to start their 88 days of regional work. Rego valid for another 4 months!',
    type: 'Station Wagon',
    equipmentState: 'À aménager',
    regoState: 'VIC',
    price: 3500,
    mileage: 198000,
    year: 2006,
    brand: 'Ford',
    model: 'Falcon Wagon',
    location: 'Dubbo',
    equipments: ['Glacière', 'Réchaud gaz', 'Roue de secours'],
    isPremium: false,
    image: 'https://images.unsplash.com/photo-1617469767053-d3b508a0d825?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Tom',
    whatsappNumber: '+447911123456',
    createdAt: '2026-05-18'
  },
  {
    id: 'ad-5',
    title: 'Toyota Hiace Hightop - Cozy Ultimate Home On Wheels',
    description: 'High roof Toyota Hiace, you can actually stand up inside! Beautiful custom wood interior built by a cabinetmaker. Generous solar system (200W solar panel + 120Ah deep cycle battery) with multiple USB ports. Beautiful convertible kitchen with sink, running water pump, and induction stove. Extremely comfortable memory foam double bed. Mechanically perfect with complete service logs. Sad to Sell as our visa is ending.',
    type: 'Van',
    equipmentState: 'Clé en main',
    regoState: 'WA',
    price: 16500,
    mileage: 330000,
    year: 2004,
    brand: 'Toyota',
    model: 'Hiace',
    location: 'Melbourne',
    equipments: ['Panneaux solaires', 'Lit convertible', 'Évier avec pompe', 'Second Battery', 'Frigo', 'Convertisseur 12v-220v', 'Douche de camping'],
    isPremium: true,
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Pierre & Sarah',
    whatsappNumber: '+33688888888',
    createdAt: '2026-05-21'
  },
  {
    id: 'ad-6',
    title: 'Nissan Patrol 4.2L Turbo Diesel - indestructible Outback Build',
    description: 'The legendary TD42 Nissan Patrol. Prepped for absolute remote off-grid exploration. Complete with iron bullbar, winch, dual battery system with smart isolator, air compressor mounted under the hood, snorkel, drawers, and fridge. Top bed deck inside or rooftop mount friendly. Highly sought-after engine. Ready for Darwin/Alice Springs tracks.',
    type: '4x4',
    equipmentState: 'À aménager',
    regoState: 'NT',
    price: 18000,
    mileage: 295000,
    year: 2001,
    brand: 'Nissan',
    model: 'Patrol',
    location: 'Alice Springs',
    equipments: [' snorkel', 'Treuil', 'Compresseur d\'air', 'Sangles de remorquage', 'Second Battery'],
    isPremium: false,
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800',
    sellerName: 'William',
    whatsappNumber: '+61412345678',
    createdAt: '2026-05-15'
  },
  {
    id: 'ad-7',
    title: 'Mercedes Sprinter LWB - Luxury High-Roof Camper (Fully Off-Grid)',
    description: 'Looking for maximum comfort? This Sprinter has it all: Hot water shower installed, diesel heater for the freezing desert nights, massive 300W solar panels, premium lithium batteries (LiFePO4), dynamic sound system, and a gas oven. WA rego ready, fully certified gas installation. Serviced only at certified mechanics. Ideal for a long couple trip around Australia.',
    type: 'Van',
    equipmentState: 'Clé en main',
    regoState: 'WA',
    price: 24500,
    mileage: 260000,
    year: 2011,
    brand: 'Mercedes-Benz',
    model: 'Sprinter',
    location: 'Melbourne',
    equipments: ['Panneaux solaires', 'Douche chaude', 'Chauffage diesel', 'Second Battery', 'Frigo', 'Four & Réchaud', 'Lit permanent'],
    isPremium: false,
    image: 'https://images.unsplash.com/photo-1542435503-956c469947f6?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Jules & Emma',
    whatsappNumber: '+33622446688',
    createdAt: '2026-05-19'
  },
  {
    id: 'ad-8',
    title: 'Mitsubishi Pajero 4x4 - Ideal Duo Adventurer',
    description: 'Extremely good compromise between driving comfort and off-road capability. Pajero with Super Select 4WD system. Rear features a custom platform where you can sleep interiorly, or put the included premium pop-up dome tent. Fully serviced recently with new alternator & radiator. Includes WA Rego renewed for 6 months! Perfect to drive on the pristine sand of Fraser Island or Lucky Bay.',
    type: '4x4',
    equipmentState: 'Clé en main',
    regoState: 'WA',
    price: 7200,
    mileage: 275000,
    year: 2004,
    brand: 'Mitsubishi',
    model: 'Pajero',
    location: 'Perth',
    equipments: ['Matelas arrière', 'Glacière', 'Réchaud gaz', 'Ustensiles de cuisine', 'Équipement de snorkeling'],
    isPremium: false,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800',
    sellerName: 'Arthur',
    whatsappNumber: '+33677777777',
    createdAt: '2026-05-24'
  }
];

export const EQUIPMENTS_OPTIONS = [
  'Lit double / convertible',
  'Second Battery (Batterie Auxiliaire)',
  'Frigo / Glacière électrique',
  'Glacière simple (Icebox)',
  'Panneaux solaires',
  'Tente de toit (Rooftop Tent)',
  'Réchaud à gaz + bouteilles',
  'Ustensiles de cuisine complets',
  'Réservoir d\'eau (Water tank)',
  'Douche solaire / de camping',
  'Compresseur d\'air (Pneus gonflage)',
  'Sangles de remorquage & plaques de désensablage (MaxTrax)',
  'Convertisseur 12V-220V',
  'Rangement tiroirs en bois',
  'Table + chaises de camping',
  'Snorkel & équipement 4x4',
  'Équipement de snorkeling (Palmes, masque)'
];

export const AUSTRALIAN_STATES_DESC = {
  WA: {
    fullName: 'Western Australia (Perth)',
    color: 'bg-emerald-600',
    badge: 'border-emerald-200 text-emerald-800 bg-emerald-50',
    requirements: 'Pas de contrôle technique (RWC) requis pour le transfert. Tout se fait en ligne depuis leur plateforme DOT. Recommandé n°1 pour les backpackers.',
    cost: 'Moyen',
  },
  QLD: {
    fullName: 'Queensland (Brisbane, Cairns)',
    color: 'bg-amber-600',
    badge: 'border-amber-200 text-amber-800 bg-amber-50',
    requirements: 'Contrôle technique ("Safety Certificate") obligatoire de moins de 2 mois pour vendre. Sinon, plaques à rendre avant la transaction.',
    cost: 'Abordable',
  },
  NSW: {
    fullName: 'New South Wales (Sydney)',
    color: 'bg-blue-600',
    badge: 'border-blue-200 text-blue-800 bg-blue-50',
    requirements: 'Inspection mécanique annuelle obligatoire ("Pink Slip") pour pouvoir renouveler. Très strict sur la sécurité et la rouille.',
    cost: 'Élevé',
  },
  VIC: {
    fullName: 'Victoria (Melbourne)',
    color: 'bg-indigo-600',
    badge: 'border-indigo-200 text-indigo-800 bg-indigo-50',
    requirements: 'Roadworthy Certificate (RWC) obligatoire fourni par le vendeur pour réaliser la vente. Inspection complète et parfois coûteuse.',
    cost: 'Élevé',
  },
  SA: {
    fullName: 'South Australia (Adelaide)',
    color: 'bg-rose-600',
    badge: 'border-rose-200 text-rose-800 bg-rose-50',
    requirements: 'Plutôt simple, pas d\'inspection mécanique nécessaire sauf en cas d\'importation d\'un autre État.',
    cost: 'Abordable',
  },
  NT: {
    fullName: 'Northern Territory (Darwin)',
    color: 'bg-orange-600',
    badge: 'border-orange-200 text-orange-800 bg-orange-50',
    requirements: 'Nécessite une inspection de sécurité périodique pour les véhicules de plus de 5 ou 10 ans.',
    cost: 'Moyen',
  },
  TAS: {
    fullName: 'Tasmania (Hobart)',
    color: 'bg-teal-600',
    badge: 'border-teal-200 text-teal-800 bg-teal-50',
    requirements: 'Pas de contrôle technique obligatoire pour la vente, transfert simple sur papier ou sur place.',
    cost: 'Abordable',
  }
};
